### ISSUE TITLE
Rename SonarRanges.msg

### ISSUE THREAD

**Issue by lauralindzey** [apl-ocean-engineering/hydrographic_msgs#16]
As discussed in #3, the current name is confusing because:
* The message actually reports travel times, rather than directly converting them to ranges
* It has a lot of fields that are clearly aimed at MBES instruments.

@valschmidt suggested using MBES in the name, and maybe rawMBES.

Other ideas/suggestions?

**Comment by CaptKrasno** [comment]
MBES or  rawMBES sounds ok to me.   I think I prefer MBES.  This is fundamentally the type of data the MBES produce.  I think "raw" is redundant and does not match the convention with most other ROS types in my experience.

**Comment by lauralindzey** [comment]
Other options: What about just `Multibeam.msg`? `MultibeamEcho.msg`?

(Brainstorming, not advocating.)

**Comment by CaptKrasno** [comment]
I like MultibeamEcho or how about MultibeamDetections.   We aren't really reporting raw multibeam data. We are reporting what the MBES detected and reported to us.  

so how about something like: 

- MultibeamEcho/Detections:  for detected returns 
- MultibeamWatercolumn:  for intensities over time and for each rx-angle
- MultibeamRaw:  For all phase/intensity information needed to generate bearings, travel times, and detections.   Maybe implement this in the future,  haven't encountered a sonar that reports this to users.

**Comment by lauralindzey** [comment]
I'm currently on a call w/ @tfoote, and he made some good comments about this issue:
* Multibeam will be confusing for people not already immersed in the marine community, because there are plenty of sensors with multiple beams
* If we want this message to be used broadly, Watercolumn is overly specific.

How about:
* SonarDetections
* SonarImage

or, if we want to be very descriptive:
* MultibeamSonarDetections
* MultibeamSonarImage

**Comment by CaptKrasno** [comment]
I would stay away from Sonar* naming because the geometry associated with this message is intended to be specific to multibeams.

I vote for MultibeamSonar*  or MBES* for brevity.

*Image and *Detections sound ok to me.

**Comment by tfoote** [comment]
From the viewpoint of someone who may search for the messages it's important to not just have the acronyms in the names. Verbose and searchable is better. In the code it gets compiled away or you can use shortcuts/aliases.

Though I understand that these are specifically for multibeam sonar. What are the potential other datatypes for other sonars? Can they have Sonar<Xxxx> which would clearly distinguish them? If it's not multibeam is a single beam or point or just a sensor_msgs/Range?

**Comment by lauralindzey** [comment]
This has been resolved: we now have `SonarDetections.msg` for time-domain, and `SonarRanges.msg` for data that has been processed to return distances.
