### ISSUE TITLE
ROS2

### ISSUE THREAD

**Issue by CaptKrasno** [apl-ocean-engineering/hydrographic_msgs#30]
I am working on a new sonar driver that will launch as a ROS2 node.  I would like it to support the hyrdrographic messages standards.

Has anyone started porting Hydrograpic_msgs to ros2?   If not.  I will fork and start updating it later this week and make a pull request soon.

@lauralindzey 
@rolker 

-Kris

**Comment by vatanaksoytezer** [comment]
İt is not ported to ROS2 as we are speaking but if there is need I can do it today.

**Comment by lauralindzey** [comment]
@CaptKrasno -- I met @vatanaksoytezer at ROSCon and he has been enthusiastic about helping out on the parts of package maintaintership I'm weakest at. 

I think he has a plan for how to handle dual ROS1/ROS2 support, so I'm assigning this to him. 

What sonar will this be for? (and if you're allowed to say...what platform?)

**Comment by CaptKrasno** [comment]
@vatanaksoytezer thanks for volunteering.  That's a big help.  If you can do it soon that would be great.   I will be working the driver tomorrow afternoon and Friday.  

@lauralindzey I am now working with University of South Florida's COMIT group.  I am getting their open source software presence set up and they have an existing relationship with R2Sonic.   The ROS2 R2Sonic driver seemed like a good first project to get something useful on the GitHub. We plan to use it on some of the surface vessels for testing future ROS projects.   Check out COMIT Github page [https://github.com/USF-COMIT](https://github.com/USF-COMIT) .   We should have our first pre-release of the driver in  about a week.  Some more substantial projects should be coming online soon after!

-Kris

**Comment by vatanaksoytezer** [comment]
@CaptKrasno @lauralindzey ported at #32 with some cleanups.

**Comment by vatanaksoytezer** [comment]
Closing as completed, thank you for reviewing! @lauralindzey once we resolve the naming issue, I will release for ROS2 as well.
