### ISSUE TITLE
Beam Angle nomenclature

### ISSUE THREAD

**Issue by lauralindzey** [apl-ocean-engineering/hydrographic_msgs#9]
One of the first things to come up when discussion sonar-specific messages was how to specify the beam angle for messages that are applicable to multibeam and imaging sonars. So far, I've seen three different proposals:

1) along/across track
2) azimuth/elevation
3) tx/rx angle

* tx/rx angle is potentially limiting because it's multibeam-specific and does not make sense for imaging sonars. 
* along/across track assumes that you're doing bathymetric mapping, which is a major use case but far from the only one. For example, I've worked with a vehicle that mounted a multibeam with the fan pointed out the port side, and executed a roll maneuver to get a 3D point cloud. I've also seen these sensors mounted on a nodding or rolling sensor head. In all of these cases, I'm not sure how you'd define along/across track.

I'd love alternatives to azimuth/elevation, because I don't necessarily think that it's the most intuitive terminlogy, although it is what is most commonly used in the imaging sonar literature.

**Comment by CaptKrasno** [comment]
![rx_azimuth_compare](https://user-images.githubusercontent.com/23006525/110335904-58967280-7ff2-11eb-844f-7931bba90935.png)

### Quick preface

For this entire comment I am talking about a multibeam sonar.   I am not familiar enough with other types of imaging sonars to speak to them.

### Other uses of tx/rx angle nomenclature

These are the common data formats I deal with, all using tx/rx angle.  

[s7k format](https://www3.mbari.org/data/mbsystem/formatdoc/Reson/Reson7kDataFormatVolumeIVersion2.22.pdf)  section 10.37
[norbit multibeam format](https://www.dropbox.com/s/r7c2x8aclcr5vf0/TN-180196-1D-WBMS_DFD_External.pdf?dl=0) section 8.1
[WASSP multibeam data format](https://www.dropbox.com/s/mp6tnl6wbqvw7yy/WASSP%20DRX%20ICD%202.79.pdf?dl=0) section 4.6.2

### My issue with azimuth and elevation

After thinking through this I realized that the azimuth and elevation model does not accurately describe the geometry.   Elevation describes the angle between a line and it's projection into a plane,  this is physically correct and is ok for tx/along track angle.   However, azimuth describes a rotation about an axis which is NOT what is what the sonar is reporting.  Tx/Rx or along/across track described 2 elevations which is what is physically being measured.

This is an important distinction when projecting multibeam points.  Imagine fixing one variable and letting the other vary...    When we do this for elevations we constrain the geometry to a cone where azimuths constrain geometry to a plane.   

![mp_cones](https://user-images.githubusercontent.com/23006525/110337923-6c42d880-7ff4-11eb-917c-0027d020c5a4.jpeg)
This figure shows the intersection of the tx cone (orange) and the rx cone (blue).   The detected beam can be thought of as the intersection of the two cones.   This beam could be accurately described with azimuth and elevation with some conversion.  However...

![mp_cones_translated](https://user-images.githubusercontent.com/23006525/110338277-d0fe3300-7ff4-11eb-8e14-ed85a54facd6.jpeg)
The geometry becomes particularly when the rx cone is allowed to translate and rotate durring the 2 way travel time, as it would  on a rolling/moving ship.  This geometry can not be accurately described as an azimuth and elevation.

**Comment by CaptKrasno** [comment]
@lauralindzey @bsb808 
I would like to propose we close this issue for now and move it into a pull request.   We haven't had any input in a while and I would like to keep this part of the project project moving.   

How can we decide which nomenclature to settle on?   



>     * tx/rx angle is potentially limiting because it's multibeam-specific and does not make sense for imaging sonars.

@lauralindzey I want to be very careful with the geometry we are reporting.   (see my last comment)   If the geometry is actually different.  Maybe we should have 2 different messages for imaging and multibeam sonars.

**Comment by lauralindzey** [comment]
Ugh, yeah. Thanks for the careful explanation. (And the use cases so far from mine!)

I think you've convinced me about rx/tx for message types meant for multibeam sonars.

**Comment by lauralindzey** [comment]
Resolved. `SonarDetections.msg` and `RawSonarImage.msg` both use {rx,tx}_angles now.
